export const rentalCategories = [
  { slug: 'car-rentals', label: 'Car Rentals', description: 'Luxury cars and premium experiences.' },
  { slug: 'yacht-rentals', label: 'Yacht Rentals', description: 'Private yacht experiences for nightlife, events, and luxury outings.' },
  { slug: 'vacation-rentals', label: 'Vacation Rentals', description: 'Short-term stays, villas, and premium residences in key markets.' },
  { slug: 'miami-experiences', label: 'Miami Experiences', description: 'Private dining, nightlife, and premium events.' }
];

const rentals = [
  {
    id: 'mercedes-g63-amg',
    slug: 'mercedes-g63-amg',
    title: 'Mercedes G63 AMG',
    company: 'Elite Miami Rentals',
    category: 'Luxury Cars',
    categorySlug: 'car-rentals',
    location: 'Miami Beach',
    dailyPrice: '$320',
    weeklyPrice: '$1,850',
    monthlyPrice: '$6,200',
    securityDeposit: '$1,500',
    availability: 'Available today',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
    description: 'V8-powered luxury SUV with concierge delivery and premium airport pickup.',
    featured: true
  },
  {
    id: 'lamborghini-huracan',
    slug: 'lamborghini-huracan',
    title: 'Lamborghini Huracan',
    company: 'VIP Drive Club',
    category: 'Luxury Cars',
    categorySlug: 'car-rentals',
    location: 'South Miami',
    dailyPrice: '$480',
    weeklyPrice: '$2,900',
    monthlyPrice: '$9,700',
    securityDeposit: '$2,000',
    availability: 'Limited weekend slots',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=80',
    description: 'A dramatic supercar experience for nightlife, events, and premium weekend travel.',
    featured: true
  },
  {
    id: 'ferrari-f8',
    slug: 'ferrari-f8',
    title: 'Ferrari F8',
    company: 'Miami Supercar Rentals',
    category: 'Sports Cars',
    categorySlug: 'car-rentals',
    location: 'Brickell',
    dailyPrice: '$620',
    weeklyPrice: '$3,900',
    monthlyPrice: '$12,500',
    securityDeposit: '$2,500',
    availability: 'Available this week',
    image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
    description: 'Performance-focused luxury coupe with premium delivery and valet-ready styling.',
    featured: true
  },
  {
    id: 'rolls-royce-cullinan',
    slug: 'rolls-royce-cullinan',
    title: 'Rolls Royce Cullinan',
    company: 'Prestige Mobility',
    category: 'Luxury Cars',
    categorySlug: 'car-rentals',
    location: 'Bal Harbour',
    dailyPrice: '$720',
    weeklyPrice: '$4,500',
    monthlyPrice: '$14,200',
    securityDeposit: '$3,000',
    availability: 'Available next 48hrs',
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
    description: 'Full-size ultra-luxury SUV for executive transport, airport transfers, and VIP events.',
    featured: true
  },
  {
    id: 'porsche-911',
    slug: 'porsche-911',
    title: 'Porsche 911',
    company: 'Ocean Drive Rentals',
    category: 'Luxury Cars',
    categorySlug: 'car-rentals',
    location: 'Downtown Miami',
    dailyPrice: '$280',
    weeklyPrice: '$1,600',
    monthlyPrice: '$5,400',
    securityDeposit: '$1,300',
    availability: 'Booking window open',
    image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80',
    description: 'Timeless sports car with polished finishes and premium weekend availability.',
    featured: false
  },
  {
    id: 'range-rover',
    slug: 'range-rover',
    title: 'Range Rover',
    company: 'The Island Fleet',
    category: 'SUVs',
    categorySlug: 'car-rentals',
    location: 'Aventura',
    dailyPrice: '$260',
    weeklyPrice: '$1,500',
    monthlyPrice: '$4,900',
    securityDeposit: '$1,200',
    availability: 'Available now',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
    description: 'Refined all-terrain SUV for upscale travel, resort transfers, and family-style comfort.',
    featured: false
  },
  {
    id: 'bmw-m8',
    slug: 'bmw-m8',
    title: 'BMW M8',
    company: 'Grand Avenue Rentals',
    category: 'Luxury Cars',
    categorySlug: 'car-rentals',
    location: 'Wynwood',
    dailyPrice: '$340',
    weeklyPrice: '$2,050',
    monthlyPrice: '$6,900',
    securityDeposit: '$1,600',
    availability: 'High demand',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
    description: 'Executive luxury coupe with premium cabin features and quick airport pickup.',
    featured: false
  },
  {
    id: 'corvette-c8',
    slug: 'corvette-c8',
    title: 'Corvette C8',
    company: 'Palm Rentals',
    category: 'Sports Cars',
    categorySlug: 'car-rentals',
    location: 'Coconut Grove',
    dailyPrice: '$360',
    weeklyPrice: '$2,200',
    monthlyPrice: '$7,300',
    securityDeposit: '$1,800',
    availability: 'Limited availability',
    image: 'https://images.unsplash.com/photo-1549399525-7f4f2a0a5f6d?auto=format&fit=crop&w=900&q=80',
    description: 'American performance icon with low-mileage availability and premium concierge support.',
    featured: false
  },
  {
    id: 'azimut-flybridge-60',
    slug: 'azimut-flybridge-60',
    title: '60ft Azimut Flybridge Yacht',
    company: 'Sunset Harbour Yachts',
    category: 'Motor Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Miami Beach Marina',
    dailyPrice: '$2,200',
    weeklyPrice: '$13,500',
    monthlyPrice: 'Charter only',
    securityDeposit: '$5,000',
    availability: 'Available today',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Spacious flybridge yacht with sundeck, ideal for day charters and sunset cruises around Biscayne Bay.',
    featured: true
  },
  {
    id: 'sunseeker-predator-75',
    slug: 'sunseeker-predator-75',
    title: '75ft Sunseeker Predator',
    company: 'Las Olas Yacht Charters',
    category: 'Sport Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Fort Lauderdale',
    dailyPrice: '$3,400',
    weeklyPrice: '$21,000',
    monthlyPrice: 'Charter only',
    securityDeposit: '$7,500',
    availability: 'Limited weekend slots',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'High-performance sport yacht with sleek styling, popular for Fort Lauderdale nightlife runs.',
    featured: true
  },
  {
    id: 'sea-ray-sundancer-50',
    slug: 'sea-ray-sundancer-50',
    title: '50ft Sea Ray Sundancer',
    company: 'Biscayne Bay Boat Club',
    category: 'Sport Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Key Biscayne',
    dailyPrice: '$1,600',
    weeklyPrice: '$9,800',
    monthlyPrice: 'Charter only',
    securityDeposit: '$3,000',
    availability: 'Available this week',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Comfortable mid-size cruiser perfect for small groups exploring Key Biscayne and Stiltsville.',
    featured: false
  },
  {
    id: 'ferretti-yacht-80',
    slug: 'ferretti-yacht-80',
    title: '80ft Ferretti Yacht',
    company: 'Ocean Drive Yacht Rentals',
    category: 'Motor Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Miami Beach',
    dailyPrice: '$4,800',
    weeklyPrice: '$29,500',
    monthlyPrice: 'Charter only',
    securityDeposit: '$9,000',
    availability: 'Available next 48hrs',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Full-beam luxury motor yacht with three staterooms and a professional crew for VIP charters.',
    featured: true
  },
  {
    id: 'fountaine-pajot-catamaran-45',
    slug: 'fountaine-pajot-catamaran-45',
    title: '45ft Fountaine Pajot Catamaran',
    company: 'Grove Sailing Charters',
    category: 'Catamaran',
    categorySlug: 'yacht-rentals',
    location: 'Coconut Grove',
    dailyPrice: '$1,400',
    weeklyPrice: '$8,500',
    monthlyPrice: 'Charter only',
    securityDeposit: '$2,500',
    availability: 'Available now',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Stable, spacious catamaran ideal for family outings and calm-water sailing around Coconut Grove.',
    featured: false
  },
  {
    id: 'viking-sport-yacht-65',
    slug: 'viking-sport-yacht-65',
    title: '65ft Viking Sport Yacht',
    company: 'Haulover Luxury Charters',
    category: 'Sport Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Haulover Marina',
    dailyPrice: '$2,900',
    weeklyPrice: '$17,500',
    monthlyPrice: 'Charter only',
    securityDeposit: '$6,000',
    availability: 'Booking window open',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Sport fishing convertible turned luxury charter, fast and stable for offshore Miami runs.',
    featured: false
  },
  {
    id: 'lazzara-motor-yacht-90',
    slug: 'lazzara-motor-yacht-90',
    title: '90ft Lazzara Motor Yacht',
    company: 'Fisher Island Yacht Club',
    category: 'Motor Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Fisher Island',
    dailyPrice: '$6,500',
    weeklyPrice: '$39,000',
    monthlyPrice: 'Charter only',
    securityDeposit: '$12,000',
    availability: 'Limited availability',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Flagship motor yacht with wraparound deck and formal dining salon, based at Fisher Island.',
    featured: true
  },
  {
    id: 'princess-flybridge-55',
    slug: 'princess-flybridge-55',
    title: '55ft Princess Flybridge',
    company: 'Bal Harbour Marine',
    category: 'Motor Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Bal Harbour',
    dailyPrice: '$2,300',
    weeklyPrice: '$14,000',
    monthlyPrice: 'Charter only',
    securityDeposit: '$4,500',
    availability: 'Available today',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Elegant flybridge cruiser with a sun pad and wet bar, moored minutes from Bal Harbour Shops.',
    featured: false
  },
  {
    id: 'pontoon-party-yacht-40',
    slug: 'pontoon-party-yacht-40',
    title: '40ft Pontoon Party Yacht',
    company: 'South Beach Boat Rentals',
    category: 'Party Yacht',
    categorySlug: 'yacht-rentals',
    location: 'South Beach',
    dailyPrice: '$900',
    weeklyPrice: '$5,200',
    monthlyPrice: 'Charter only',
    securityDeposit: '$1,500',
    availability: 'High demand',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Open-deck party pontoon with sound system, built for South Beach sunset gatherings.',
    featured: false
  },
  {
    id: 'hatteras-yacht-70',
    slug: 'hatteras-yacht-70',
    title: '70ft Hatteras Yacht',
    company: 'Port Everglades Yachts',
    category: 'Motor Yacht',
    categorySlug: 'yacht-rentals',
    location: 'Fort Lauderdale',
    dailyPrice: '$3,100',
    weeklyPrice: '$19,000',
    monthlyPrice: 'Charter only',
    securityDeposit: '$6,500',
    availability: 'Available this week',
    image: '/images/rentals/yacht-placeholder.svg',
    description: 'Classic Hatteras motor yacht with a raised pilothouse, based out of Port Everglades.',
    featured: false
  },
  {
    id: 'oceanfront-villa-miami-beach',
    slug: 'oceanfront-villa-miami-beach',
    title: 'Oceanfront Villa',
    company: 'Sunset Villas Group',
    category: 'Villa',
    categorySlug: 'vacation-rentals',
    location: 'Miami Beach',
    dailyPrice: '$650',
    weeklyPrice: '$3,900',
    monthlyPrice: '$12,500',
    securityDeposit: '$2,000',
    availability: 'Available today',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Six-bedroom oceanfront villa with private beach access and an infinity pool overlooking the Atlantic.',
    featured: true
  },
  {
    id: 'modern-penthouse-brickell',
    slug: 'modern-penthouse-brickell',
    title: 'Modern Penthouse',
    company: 'Brickell Skyline Residences',
    category: 'Penthouse',
    categorySlug: 'vacation-rentals',
    location: 'Brickell',
    dailyPrice: '$520',
    weeklyPrice: '$3,100',
    monthlyPrice: '$9,800',
    securityDeposit: '$1,800',
    availability: 'Available this week',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Floor-to-ceiling glass penthouse with skyline views, a rooftop terrace, and private elevator access.',
    featured: true
  },
  {
    id: 'waterfront-estate-coral-gables',
    slug: 'waterfront-estate-coral-gables',
    title: 'Waterfront Estate',
    company: 'Coral Gables Luxury Homes',
    category: 'Estate',
    categorySlug: 'vacation-rentals',
    location: 'Coral Gables',
    dailyPrice: '$780',
    weeklyPrice: '$4,600',
    monthlyPrice: '$14,500',
    securityDeposit: '$2,500',
    availability: 'Booking window open',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Mediterranean-style waterfront estate with a private dock, formal gardens, and guest house.',
    featured: false
  },
  {
    id: 'private-pool-villa-coconut-grove',
    slug: 'private-pool-villa-coconut-grove',
    title: 'Private Pool Villa',
    company: 'Grove Estate Rentals',
    category: 'Villa',
    categorySlug: 'vacation-rentals',
    location: 'Coconut Grove',
    dailyPrice: '$410',
    weeklyPrice: '$2,450',
    monthlyPrice: '$7,600',
    securityDeposit: '$1,300',
    availability: 'Available now',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Tropical-landscaped villa with a private pool and outdoor kitchen minutes from the Grove marina.',
    featured: false
  },
  {
    id: 'beachfront-condo-fort-lauderdale',
    slug: 'beachfront-condo-fort-lauderdale',
    title: 'Beachfront Condo',
    company: 'Las Olas Beach Rentals',
    category: 'Condo',
    categorySlug: 'vacation-rentals',
    location: 'Fort Lauderdale',
    dailyPrice: '$340',
    weeklyPrice: '$2,050',
    monthlyPrice: '$6,400',
    securityDeposit: '$1,000',
    availability: 'Limited weekend slots',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Two-bedroom beachfront condo steps from Las Olas Boulevard dining and nightlife.',
    featured: false
  },
  {
    id: 'key-west-cottage',
    slug: 'key-west-cottage',
    title: 'Key West Cottage',
    company: 'Old Town Key West Rentals',
    category: 'Cottage',
    categorySlug: 'vacation-rentals',
    location: 'Key West',
    dailyPrice: '$290',
    weeklyPrice: '$1,750',
    monthlyPrice: '$5,400',
    securityDeposit: '$900',
    availability: 'Available today',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Classic conch-style cottage in Old Town with a private courtyard and a short walk to Duval Street.',
    featured: false
  },
  {
    id: 'golf-course-villa-doral',
    slug: 'golf-course-villa-doral',
    title: 'Golf Course Villa',
    company: 'Doral Resort Homes',
    category: 'Villa',
    categorySlug: 'vacation-rentals',
    location: 'Doral',
    dailyPrice: '$360',
    weeklyPrice: '$2,150',
    monthlyPrice: '$6,700',
    securityDeposit: '$1,100',
    availability: 'Available this week',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Fairway-facing villa with resort-style amenities and easy access to Miami International Airport.',
    featured: false
  },
  {
    id: 'bayfront-penthouse-edgewater',
    slug: 'bayfront-penthouse-edgewater',
    title: 'Bayfront Penthouse',
    company: 'Bay Skyline Rentals',
    category: 'Penthouse',
    categorySlug: 'vacation-rentals',
    location: 'Edgewater',
    dailyPrice: '$480',
    weeklyPrice: '$2,850',
    monthlyPrice: '$9,000',
    securityDeposit: '$1,600',
    availability: 'High demand',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Bay-view penthouse with a wraparound balcony overlooking Biscayne Bay and the Miami skyline.',
    featured: false
  },
  {
    id: 'luxury-townhouse-aventura',
    slug: 'luxury-townhouse-aventura',
    title: 'Luxury Townhouse',
    company: 'Aventura Premier Homes',
    category: 'Estate',
    categorySlug: 'vacation-rentals',
    location: 'Aventura',
    dailyPrice: '$400',
    weeklyPrice: '$2,400',
    monthlyPrice: '$7,500',
    securityDeposit: '$1,200',
    availability: 'Available next 48hrs',
    image: '/images/rentals/vacation-placeholder.svg',
    description: 'Gated-community townhouse close to Aventura Mall with a private garage and rooftop lounge.',
    featured: false
  },
  {
    id: 'naples-beach-house',
    slug: 'naples-beach-house',
    title: 'Naples Beach House',
    company: 'Gulf Coast Retreats',
    category: 'Villa',
    categorySlug: 'vacation-rentals',
    location: 'Naples',
    dailyPrice: '$520',
    weeklyPrice: '$3,100',
    monthlyPrice: '$9,700',
    securityDeposit: '$1,700',
    availability: 'Available now',
    image: '/images/rentals/vacation-placeholder.svg',
    description: "Gulf-front beach house on Florida's west coast with a private boardwalk and sunset views.",
    featured: false
  },
  {
    id: 'private-chef-dinner-south-beach',
    slug: 'private-chef-dinner-south-beach',
    title: 'Private Chef Dinner',
    company: 'Miami Culinary Concierge',
    category: 'Private Dining',
    categorySlug: 'miami-experiences',
    location: 'South Beach',
    dailyPrice: '$450 per guest',
    weeklyPrice: 'Multi-night packages available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Available today',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'In-villa private chef experience featuring a custom multi-course menu and dedicated service staff.',
    featured: true
  },
  {
    id: 'rooftop-nightclub-table-downtown',
    slug: 'rooftop-nightclub-table-downtown',
    title: 'Rooftop Nightclub Table Service',
    company: 'Skyline Nightlife Group',
    category: 'Nightlife',
    categorySlug: 'miami-experiences',
    location: 'Downtown Miami',
    dailyPrice: '$800 per table',
    weeklyPrice: 'Weekend packages available',
    monthlyPrice: 'N/A',
    securityDeposit: '$300 minimum spend',
    availability: 'Available this week',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'Reserved VIP table with bottle service at a downtown Miami rooftop nightclub.',
    featured: true
  },
  {
    id: 'private-yacht-sunset-party',
    slug: 'private-yacht-sunset-party',
    title: 'Private Yacht Sunset Party',
    company: 'Bay Party Experiences',
    category: 'Boat Tour',
    categorySlug: 'miami-experiences',
    location: 'Biscayne Bay',
    dailyPrice: '$1,200 for up to 12 guests',
    weeklyPrice: 'Multi-stop packages available',
    monthlyPrice: 'N/A',
    securityDeposit: '$500',
    availability: 'Available now',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'Three-hour sunset cruise around Biscayne Bay with music, catering, and open bar options.',
    featured: false
  },
  {
    id: 'wynwood-art-nightlife-tour',
    slug: 'wynwood-art-nightlife-tour',
    title: 'Wynwood Art & Nightlife Tour',
    company: 'Wynwood Experience Co.',
    category: 'Tour',
    categorySlug: 'miami-experiences',
    location: 'Wynwood',
    dailyPrice: '$120 per guest',
    weeklyPrice: 'Group rates available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Available today',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'Guided evening tour through Wynwood Walls murals, galleries, and rooftop bars.',
    featured: false
  },
  {
    id: 'vip-beach-club-cabana',
    slug: 'vip-beach-club-cabana',
    title: 'VIP Beach Club Cabana',
    company: 'Ocean Club Miami',
    category: 'VIP Event',
    categorySlug: 'miami-experiences',
    location: 'South Beach',
    dailyPrice: '$600 per day',
    weeklyPrice: 'Weekly cabana packages available',
    monthlyPrice: 'N/A',
    securityDeposit: '$200',
    availability: 'Booking window open',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: "Private beachfront cabana with a dedicated server at one of South Beach's premier clubs.",
    featured: false
  },
  {
    id: 'private-art-basel-experience',
    slug: 'private-art-basel-experience',
    title: 'Private Art Basel Experience',
    company: 'Design District Concierge',
    category: 'VIP Event',
    categorySlug: 'miami-experiences',
    location: 'Miami Design District',
    dailyPrice: '$950 per guest',
    weeklyPrice: 'Multi-day festival packages available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Limited availability',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: "Curated gallery walkthroughs and after-hours access during Miami's major art fairs.",
    featured: false
  },
  {
    id: 'speedboat-sightseeing-tour',
    slug: 'speedboat-sightseeing-tour',
    title: 'Speedboat Sightseeing Tour',
    company: 'Miami Boat Tours',
    category: 'Boat Tour',
    categorySlug: 'miami-experiences',
    location: 'Miami Marina',
    dailyPrice: '$95 per guest',
    weeklyPrice: 'Private charter rates available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Available today',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: "High-speed sightseeing tour past Star Island, Millionaire's Row, and the Miami skyline.",
    featured: false
  },
  {
    id: 'rooftop-pool-party-brickell',
    slug: 'rooftop-pool-party-brickell',
    title: 'Exclusive Rooftop Pool Party',
    company: 'Brickell Social Club',
    category: 'Nightlife',
    categorySlug: 'miami-experiences',
    location: 'Brickell',
    dailyPrice: '$75 per guest',
    weeklyPrice: 'Group and cabana packages available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'High demand',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'Daytime rooftop pool party with DJ sets and skyline views in the heart of Brickell.',
    featured: false
  },
  {
    id: 'salsa-dinner-night-little-havana',
    slug: 'salsa-dinner-night-little-havana',
    title: 'Private Salsa & Dinner Night',
    company: 'Little Havana Experiences',
    category: 'Private Dining',
    categorySlug: 'miami-experiences',
    location: 'Little Havana',
    dailyPrice: '$140 per guest',
    weeklyPrice: 'Group bookings available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Available this week',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: "Live salsa band, dinner, and a dance lesson in the heart of Little Havana's Calle Ocho.",
    featured: false
  },
  {
    id: 'helicopter-city-tour',
    slug: 'helicopter-city-tour',
    title: 'Helicopter City Tour',
    company: 'Miami Air Tours',
    category: 'Tour',
    categorySlug: 'miami-experiences',
    location: 'Miami Downtown Heliport',
    dailyPrice: '$320 per guest',
    weeklyPrice: 'Private charter rates available',
    monthlyPrice: 'N/A',
    securityDeposit: 'N/A',
    availability: 'Available next 48hrs',
    image: '/images/rentals/miami-experience-placeholder.svg',
    description: 'Aerial tour of the Miami skyline, South Beach, and Biscayne Bay by helicopter.',
    featured: false
  }
];

export function getRentals() {
  return rentals;
}

export function getFeaturedRentals() {
  return rentals.filter((item) => item.featured);
}

export function getRentalBySlug(slug) {
  return rentals.find((item) => item.slug === slug);
}

export function getRentalsByCategorySlug(categorySlug) {
  return rentals.filter((item) => item.categorySlug === categorySlug);
}

export function getRentalCategoryBySlug(categorySlug) {
  return rentalCategories.find((category) => category.slug === categorySlug);
}
