import fs from 'fs';

const path = 'C:\\Users\\alexa\\.gemini\\antigravity-ide\\scratch\\Gorgona-one-claude\\lib\\i18n.js';
let content = fs.readFileSync(path, 'utf8');

const translations = {
  ja: {
    navAdditions: "travel: '旅行', villas: 'ヴィラ', yachts: 'ヨット', cars: '車', discovery: 'ディスカバリールーム'",
    homeAdditions: "heroEyebrow: 'グローバルディール · プロモコード · ライフスタイル', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'マーケットプレイスを見る', browseDeals: 'ディールを探す', askConcierge: 'コンシェルジュに尋ねる', scrollExplore: 'スクロールして探索', aiEyebrow: 'Gorgona One AI', aiTitle: 'AIに希望を伝えてください。エコシステムを見つけます。', aiLede: '検索ボックスではありません — GORGONA ONEのインテリジェンス層です。意図を、あなたの言語で、音声またはテキストで尋ねてください。', ecosystemEyebrow: 'エコシステム', ecosystemTitle: '8つの世界。1つのメンバーシップ。', ecosystemLede: '旅行、ショッピング、滞在、ヨット、車、スポーツベッティング、イベント、AIコンシェルジュ — すべての体験が一つのラグジュアリーなデザイン言語に包まれています。', partnerEyebrow: 'GORGONA ONEと提携する', partnerTitle: 'ラグジュアリーなエコシステムにあなたのブランドを。', partnerLede: '認証済みディールを公開し、複数の場所を管理し、すべてのセクションでプレミアムなグローバルオーディエンスにリーチします。', joinPartner: 'パートナーとして参加', signIn: 'サインイン'",
    rentalsAdditions: "fleet: 'フリート', collections: 'コレクション', conciergeDelivery: 'コンシェルジュによる配達', beyond: 'その他', conciergeEyebrow: 'コンシェルジュ', unforgettable: '忘れられない乗り物で到着', whiteGlove: 'ホワイトグローブのピックアップ、ヴィラやマリーナへの配達、そしてすべてのマイルで待機するコンシェルジュ。', askConcierge: 'コンシェルジュに尋ねる'",
    ai: "listening: 'リスニング中', surfacing: '検索中', light: 'ライト', dark: 'ダーク', switchToLight: 'ライトな雰囲気に切り替え', switchToDark: 'ダークな雰囲気に切り替え', askPlaceholder: 'Gorgona One AIに尋ねる', stopListening: 'リスニングを停止', speakRequest: 'リクエストを話してください', discoveryRoom: 'ディスカバリールーム', askAnywhere: 'どこからでも尋ねる…', ask: '尋ねる', results: '結果', saved: '保存済み', pinResults: '結果をピン留めしてここに保存 — ブラウジング中も残ります。', recentSearches: '最近の検索', clear: 'クリア', searchesKept: '検索結果はここに表示され、サイト全体で保持されます。', reuseSearch: 'この検索を再利用', returnToAI: 'Gorgona One AIに戻る', removeFromSaved: '保存済みから削除', save: '保存', closeAI: 'Gorgona One AIを閉じる', openAI: 'Gorgona One AIを開く'",
    discovery: "travel: '旅行', flights: 'フライト', hotels: 'ホテル', carRentals: 'レンタカー', cars: '車', yachts: 'ヨット', shopping: 'ショッピング', fashion: 'ファッション', beauty: '美容', electronics: '電子機器', entertainment: 'エンターテイメント', events: 'イベント', sports: 'スポーツ', sportsbooks: 'スポーツベッティング', food: 'フード', restaurants: 'レストラン', concierge: 'コンシェルジュ', promoCodes: 'プロモコード', deals: 'ディール'",
    constellations: "travel: '旅行の世界', drive: 'ドライブ＆セーリング', style: 'スタイル＆ショッピング', play: 'プレイ＆勝利', taste: 'テーブル＆テイスト', concierge: 'コンシェルジュ'",
    footer: "ecosystemTitle: 'エコシステム', companyTitle: '会社概要', legalTitle: '法的情報', desc: '旅行、ショッピング、滞在、ヨット、車、スポーツベッティング、イベント、AIコンシェルジュのためのラグジュアリーエコシステム — 認証済みディールとプレミアムな体験を一つの目的地で。', copyright: '© 2026 GORGONA ONE. プレミアムディール、認証済みオファー、アフィリエイト収益化に対応。', tagline: '統合されたラグジュアリーエコシステム', partnerPortal: 'パートナーポータル', becomePartner: 'パートナーになる', admin: '管理者', privacy: 'プライバシー', terms: '利用規約', affiliateDisclosure: 'アフィリエイト開示', cookiePolicy: 'Cookieポリシー'"
  },
  ko: {
    navAdditions: "travel: '여행', villas: '빌라', yachts: '요트', cars: '자동차', discovery: '디스커버리 룸'",
    homeAdditions: "heroEyebrow: '글로벌 딜 · 프로모션 코드 · 라이프스타일 혜택', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: '마켓플레이스 탐색', browseDeals: '특가 상품 보기', askConcierge: '컨시어지에게 문의', scrollExplore: '스크롤하여 탐색', aiEyebrow: 'Gorgona One AI', aiTitle: '원하는 것을 AI에게 말하세요. 생태계를 찾아줍니다.', aiLede: '검색창이 아닙니다 — GORGONA ONE의 인텔리전스 계층입니다. 당신의 언어로, 음성이나 텍스트로 의도를 묻습니다.', ecosystemEyebrow: '생태계', ecosystemTitle: '8개의 세계. 하나의 멤버십.', ecosystemLede: '여행, 쇼핑, 숙박, 요트, 자동차, 스포츠북, 이벤트, AI 컨시어지 — 모든 경험이 하나의 럭셔리 디자인 언어로 통합됩니다.', partnerEyebrow: 'GORGONA ONE과 제휴', partnerTitle: '럭셔리 생태계에 브랜드를 소개하세요.', partnerLede: '인증된 특가를 게시하고, 여러 위치를 관리하며, 모든 섹션에서 글로벌 프리미엄 잠재 고객에게 도달하세요.', joinPartner: '파트너로 참여', signIn: '로그인'",
    rentalsAdditions: "fleet: '차량 목록', collections: '컬렉션', conciergeDelivery: '컨시어지 배송', beyond: '그 너머', conciergeEyebrow: '컨시어지', unforgettable: '잊을 수 없는 모습으로 도착하세요', whiteGlove: '화이트 글로브 픽업, 빌라나 마리나로의 배송, 그리고 모든 마일에서 대기 중인 컨시어지.', askConcierge: '컨시어지에게 문의'",
    ai: "listening: '듣는 중', surfacing: '검색 중', light: '밝게', dark: '어둡게', switchToLight: '밝은 분위기로 전환', switchToDark: '어두운 분위기로 전환', askPlaceholder: 'Gorgona One AI에게 묻기', stopListening: '듣기 중지', speakRequest: '요청을 말하세요', discoveryRoom: '디스커버리 룸', askAnywhere: '어디서든 물어보세요…', ask: '질문하기', results: '결과', saved: '저장됨', pinResults: '결과를 고정하여 여기에 보관하세요 — 탐색하는 동안 유지됩니다.', recentSearches: '최근 검색', clear: '지우기', searchesKept: '검색 내역이 여기에 표시되며 사이트 전체에 유지됩니다.', reuseSearch: '이 검색 재사용', returnToAI: 'Gorgona One AI로 돌아가기', removeFromSaved: '저장된 항목에서 제거', save: '저장', closeAI: 'Gorgona One AI 단기', openAI: 'Gorgona One AI 열기'",
    discovery: "travel: '여행', flights: '항공편', hotels: '호텔', carRentals: '렌터카', cars: '자동차', yachts: '요트', shopping: '쇼핑', fashion: '패션', beauty: '뷰티', electronics: '전자제품', entertainment: '엔터테인먼트', events: '이벤트', sports: '스포츠', sportsbooks: '스포츠북', food: '음식', restaurants: '레스토랑', concierge: '컨시어지', promoCodes: '프로모션 코드', deals: '특가'",
    constellations: "travel: '여행의 세계', drive: '드라이브 & 세일링', style: '스타일 & 쇼핑', play: '플레이 & 승리', taste: '테이블 & 미각', concierge: '컨시어지'",
    footer: "ecosystemTitle: '생태계', companyTitle: '회사', legalTitle: '법적 정보', desc: '여행, 쇼핑, 숙박, 요트, 자동차, 스포츠북, 이벤트, AI 컨시어지를 위한 하나의 럭셔리 생태계 — 하나의 목적지에서 확인된 딜과 프리미엄 경험.', copyright: '© 2026 GORGONA ONE. 프리미엄 특가, 인증된 딜, 제휴 수익 창출 지원.', tagline: '통합된 럭셔리 생태계', partnerPortal: '파트너 포털', becomePartner: '파트너 되기', admin: '관리자', privacy: '개인정보 보호', terms: '이용약관', affiliateDisclosure: '제휴 공개', cookiePolicy: '쿠키 정책'"
  },
  de: {
    navAdditions: "travel: 'Reisen', villas: 'Villen', yachts: 'Yachten', cars: 'Autos', discovery: 'Entdeckungsraum'",
    homeAdditions: "heroEyebrow: 'Globale Angebote · Promo-Codes · Lifestyle-Perks', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'Marktplatz erkunden', browseDeals: 'Angebote durchsuchen', askConcierge: 'Concierge fragen', scrollExplore: 'Scrollen zum Erkunden', aiEyebrow: 'Gorgona One AI', aiTitle: 'Sagen Sie der KI, was Sie wollen. Sie findet das Ökosystem.', aiLede: 'Kein Suchfeld — GORGONA ONEs Intelligenzschicht. Fragen Sie nach Absicht, in Ihrer Sprache, per Sprache oder Text.', ecosystemEyebrow: 'Das Ökosystem', ecosystemTitle: 'Acht Welten. Eine Mitgliedschaft.', ecosystemLede: 'Reisen, Shopping, Aufenthalte, Yachten, Autos, Sportwetten, Events und ein KI-Concierge — jedes Erlebnis verpackt in einer einzigen luxuriösen Designsprache.', partnerEyebrow: 'Partner von GORGONA ONE werden', partnerTitle: 'Platzieren Sie Ihre Marke in einem Luxus-Ökosystem.', partnerLede: 'Veröffentlichen Sie verifizierte Angebote, verwalten Sie mehrere Standorte und erreichen Sie ein globales Premium-Publikum in allen Bereichen.', joinPartner: 'Als Partner beitreten', signIn: 'Anmelden'",
    rentalsAdditions: "fleet: 'Die Flotte', collections: 'Kollektionen', conciergeDelivery: 'Concierge-Lieferung', beyond: 'und darüber hinaus', conciergeEyebrow: 'Concierge', unforgettable: 'Kommen Sie in etwas Unvergesslichem an', whiteGlove: 'White-Glove-Abholung, Lieferung zu Ihrer Villa oder Marina und ein Concierge, der bei jedem Kilometer für Sie da ist.', askConcierge: 'Concierge fragen'",
    ai: "listening: 'Zuhören', surfacing: 'Suchen', light: 'Hell', dark: 'Dunkel', switchToLight: 'Zu heller Atmosphäre wechseln', switchToDark: 'Zu dunkler Atmosphäre wechseln', askPlaceholder: 'Gorgona One AI fragen', stopListening: 'Zuhören beenden', speakRequest: 'Sprechen Sie Ihre Anfrage', discoveryRoom: 'Entdeckungsraum', askAnywhere: 'Überall fragen…', ask: 'Fragen', results: 'Ergebnisse', saved: 'Gespeichert', pinResults: 'Heften Sie Ergebnisse an, um sie hier zu behalten — sie bleiben während des Surfens.', recentSearches: 'Kürzliche Suchen', clear: 'Leeren', searchesKept: 'Ihre Suchen erscheinen hier und werden auf der gesamten Website beibehalten.', reuseSearch: 'Diese Suche wiederverwenden', returnToAI: 'Zurück zu Gorgona One AI', removeFromSaved: 'Aus Gespeichertem entfernen', save: 'Speichern', closeAI: 'Gorgona One AI schließen', openAI: 'Gorgona One AI öffnen'",
    discovery: "travel: 'Reisen', flights: 'Flüge', hotels: 'Hotels', carRentals: 'Mietwagen', cars: 'Autos', yachts: 'Yachten', shopping: 'Shopping', fashion: 'Mode', beauty: 'Beauty', electronics: 'Elektronik', entertainment: 'Unterhaltung', events: 'Events', sports: 'Sport', sportsbooks: 'Sportwetten', food: 'Essen', restaurants: 'Restaurants', concierge: 'Concierge', promoCodes: 'Promo-Codes', deals: 'Angebote'",
    constellations: "travel: 'Reisewelt', drive: 'Fahren & Segeln', style: 'Stil & Shopping', play: 'Spielen & Gewinnen', taste: 'Tisch & Geschmack', concierge: 'Concierge'",
    footer: "ecosystemTitle: 'Ökosystem', companyTitle: 'Unternehmen', legalTitle: 'Rechtliches', desc: 'Ein luxuriöses Ökosystem für Reisen, Shopping, Aufenthalte, Yachten, Autos, Sportwetten, Events und einen KI-Concierge — verifizierte Angebote und Premium-Erlebnisse an einem Ort.', copyright: '© 2026 GORGONA ONE. Premium-Angebote, verifizierte Deals und fertige Affiliate-Monetarisierung.', tagline: 'Ein vereintes Luxus-Ökosystem', partnerPortal: 'Partnerportal', becomePartner: 'Partner werden', admin: 'Admin', privacy: 'Datenschutz', terms: 'Bedingungen', affiliateDisclosure: 'Affiliate-Offenlegung', cookiePolicy: 'Cookie-Richtlinie'"
  },
  ar: {
    navAdditions: "travel: 'سفر', villas: 'فيلات', yachts: 'يخوت', cars: 'سيارات', discovery: 'غرفة الاكتشاف'",
    homeAdditions: "heroEyebrow: 'عروض عالمية · رموز ترويجية · مزايا أسلوب الحياة', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'استكشاف السوق', browseDeals: 'تصفح العروض', askConcierge: 'اسأل الكونسيرج', scrollExplore: 'قم بالتمرير للاستكشاف', aiEyebrow: 'Gorgona One AI', aiTitle: 'أخبر الذكاء الاصطناعي بما تريد. سيجد لك النظام البيئي.', aiLede: 'ليس مربع بحث — طبقة الذكاء الخاصة بـ GORGONA ONE. اسأل بالنية، بلغتك، بالصوت أو النص.', ecosystemEyebrow: 'النظام البيئي', ecosystemTitle: 'ثمانية عوالم. عضوية واحدة.', ecosystemLede: 'سفر، تسوق، إقامات، يخوت، سيارات، مراهنات رياضية، فعاليات وكونسيرج بالذكاء الاصطناعي — كل تجربة مغلفة بلغة تصميم فاخرة واحدة.', partnerEyebrow: 'كن شريكًا مع GORGONA ONE', partnerTitle: 'ضع علامتك التجارية داخل نظام بيئي فاخر.', partnerLede: 'انشر عروضًا معتمدة، وأدر مواقع متعددة، ووصل إلى جمهور عالمي متميز في كل الأقسام.', joinPartner: 'انضم كشريك', signIn: 'تسجيل الدخول'",
    rentalsAdditions: "fleet: 'الأسطول', collections: 'المجموعات', conciergeDelivery: 'توصيل الكونسيرج', beyond: 'وما بعدها', conciergeEyebrow: 'الكونسيرج', unforgettable: 'صل بشيء لا يُنسى', whiteGlove: 'استلام بخدمة القفاز الأبيض، تسليم في فيلتك أو مرسى اليخوت، وكونسيرج تحت الطلب في كل ميل.', askConcierge: 'اسأل الكونسيرج'",
    ai: "listening: 'جاري الاستماع', surfacing: 'جاري البحث', light: 'مضيء', dark: 'داكن', switchToLight: 'التبديل إلى الجو المضيء', switchToDark: 'التبديل إلى الجو الداكن', askPlaceholder: 'اسأل Gorgona One AI', stopListening: 'إيقاف الاستماع', speakRequest: 'تحدث بطلبك', discoveryRoom: 'غرفة الاكتشاف', askAnywhere: 'اسأل من أي مكان...', ask: 'اسأل', results: 'النتائج', saved: 'محفوظ', pinResults: 'ثبّت النتائج للاحتفاظ بها هنا — تظل كما هي أثناء التصفح.', recentSearches: 'عمليات البحث الأخيرة', clear: 'مسح', searchesKept: 'تظهر عمليات البحث الخاصة بك هنا ويتم الاحتفاظ بها عبر الموقع.', reuseSearch: 'إعادة استخدام هذا البحث', returnToAI: 'العودة إلى Gorgona One AI', removeFromSaved: 'إزالة من المحفوظات', save: 'حفظ', closeAI: 'إغلاق Gorgona One AI', openAI: 'فتح Gorgona One AI'",
    discovery: "travel: 'سفر', flights: 'رحلات طيران', hotels: 'فنادق', carRentals: 'تأجير سيارات', cars: 'سيارات', yachts: 'يخوت', shopping: 'تسوق', fashion: 'أزياء', beauty: 'جمال', electronics: 'إلكترونيات', entertainment: 'ترفيه', events: 'فعاليات', sports: 'رياضة', sportsbooks: 'مراهنات رياضية', food: 'طعام', restaurants: 'مطاعم', concierge: 'كونسيرج', promoCodes: 'رموز ترويجية', deals: 'عروض'",
    constellations: "travel: 'عالم السفر', drive: 'القيادة والإبحار', style: 'الأناقة والتسوق', play: 'اللعب والفوز', taste: 'الطاولة والمذاق', concierge: 'الكونسيرج'",
    footer: "ecosystemTitle: 'النظام البيئي', companyTitle: 'الشركة', legalTitle: 'قانوني', desc: 'نظام بيئي فاخر للسفر والتسوق والإقامات اليخوت والسيارات والرياضات والفعاليات وكونسيرج بالذكاء الاصطناعي — عروض معتمدة وتجارب متميزة في وجهة واحدة.', copyright: '© 2026 GORGONA ONE. عروض متميزة، وخصومات معتمدة، وتسييل الأرباح بالعمولة.', tagline: 'نظام بيئي فاخر وموحد', partnerPortal: 'بوابة الشركاء', becomePartner: 'كن شريكًا', admin: 'المشرف', privacy: 'الخصوصية', terms: 'الشروط', affiliateDisclosure: 'الإفصاح عن الشراكة', cookiePolicy: 'سياسة ملفات الارتباط'"
  },
  tr: {
    navAdditions: "travel: 'Seyahat', villas: 'Villalar', yachts: 'Yatlar', cars: 'Arabalar', discovery: 'Keşif Odası'",
    homeAdditions: "heroEyebrow: 'Küresel Fırsatlar · Promosyon Kodları · Yaşam Tarzı', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'Pazaryerini Keşfet', browseDeals: 'Fırsatlara Göz At', askConcierge: 'Konsiyerje Sor', scrollExplore: 'Keşfetmek için kaydır', aiEyebrow: 'Gorgona One AI', aiTitle: 'Yapay zekaya ne istediğinizi söyleyin. Ekosistemi o bulur.', aiLede: 'Sadece bir arama kutusu değil — GORGONA ONE\\'ın zeka katmanı. Kendi dilinizde, sesli veya yazılı olarak niyetinizle sorun.', ecosystemEyebrow: 'Ekosistem', ecosystemTitle: 'Sekiz dünya. Tek üyelik.', ecosystemLede: 'Seyahat, alışveriş, konaklama, yatlar, arabalar, spor bahisleri, etkinlikler ve bir yapay zeka konsiyerji — her deneyim tek bir lüks tasarım diliyle sarılı.', partnerEyebrow: 'GORGONA ONE ile Ortak Ol', partnerTitle: 'Markanızı lüks bir ekosistemin içine yerleştirin.', partnerLede: 'Doğrulanmış fırsatlar yayınlayın, birden fazla lokasyonu yönetin ve tüm bölümlerde küresel premium bir kitleye ulaşın.', joinPartner: 'Ortak Olarak Katıl', signIn: 'Giriş Yap'",
    rentalsAdditions: "fleet: 'Filo', collections: 'Koleksiyonlar', conciergeDelivery: 'Konsiyerj Teslimatı', beyond: 've ötesi', conciergeEyebrow: 'Konsiyerj', unforgettable: 'Unutulmaz bir şeyle gelin', whiteGlove: 'Özel teslim alım, villanıza veya marinaya teslimat ve her kilometrede nöbetçi bir konsiyerj.', askConcierge: 'Konsiyerje Sor'",
    ai: "listening: 'Dinliyor', surfacing: 'Aranıyor', light: 'Aydınlık', dark: 'Karanlık', switchToLight: 'Aydınlık atmosfere geç', switchToDark: 'Karanlık atmosfere geç', askPlaceholder: 'Gorgona One AI\\'ya Sor', stopListening: 'Dinlemeyi Durdur', speakRequest: 'İsteğinizi söyleyin', discoveryRoom: 'Keşif Odası', askAnywhere: 'Her yerden sorun…', ask: 'Sor', results: 'Sonuçlar', saved: 'Kaydedildi', pinResults: 'Sonuçları burada tutmak için sabitleyin — siz gezinirken yerlerinde kalırlar.', recentSearches: 'Son Aramalar', clear: 'Temizle', searchesKept: 'Aramalarınız burada görünür ve site genelinde saklanır.', reuseSearch: 'Bu aramayı tekrar kullan', returnToAI: 'Gorgona One AI\\'ya Dön', removeFromSaved: 'Kaydedilenlerden Çıkar', save: 'Kaydet', closeAI: 'Gorgona One AI\\'yı Kapat', openAI: 'Gorgona One AI\\'yı Aç'",
    discovery: "travel: 'Seyahat', flights: 'Uçuşlar', hotels: 'Oteller', carRentals: 'Araç Kiralama', cars: 'Arabalar', yachts: 'Yatlar', shopping: 'Alışveriş', fashion: 'Moda', beauty: 'Güzellik', electronics: 'Elektronik', entertainment: 'Eğlence', events: 'Etkinlikler', sports: 'Spor', sportsbooks: 'Spor Bahisleri', food: 'Yemek', restaurants: 'Restoranlar', concierge: 'Konsiyerj', promoCodes: 'Promosyon Kodları', deals: 'Fırsatlar'",
    constellations: "travel: 'Seyahat Dünyası', drive: 'Sürüş ve Yelken', style: 'Stil ve Alışveriş', play: 'Oyun ve Kazanma', taste: 'Masa ve Lezzet', concierge: 'Konsiyerj'",
    footer: "ecosystemTitle: 'Ekosistem', companyTitle: 'Şirket', legalTitle: 'Yasal', desc: 'Seyahat, alışveriş, konaklama, yatlar, arabalar, spor bahisleri, etkinlikler ve bir yapay zeka konsiyerji için lüks bir ekosistem — doğrulanmış fırsatlar ve tek bir noktada premium deneyimler.', copyright: '© 2026 GORGONA ONE. Premium fırsatlar, doğrulanmış indirimler ve hazır ortaklık gelirleri.', tagline: 'Birleşik lüks bir ekosistem', partnerPortal: 'Ortak Portalı', becomePartner: 'Ortak Ol', admin: 'Yönetici', privacy: 'Gizlilik', terms: 'Şartlar', affiliateDisclosure: 'Ortaklık Açıklaması', cookiePolicy: 'Çerez Politikası'"
  }
};

for (const [lang, data] of Object.entries(translations)) {
  const navRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*nav: \\{.*?)( \\},?\\n)`);
  content = content.replace(navRegex, `$1, ${data.navAdditions}$2`);
  
  const homeRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*home: \\{.*?)( \\},?\\n)`);
  content = content.replace(homeRegex, `$1, ${data.homeAdditions}$2`);
  
  const rentalsRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*rentals: \\{.*?)( \\},?\\n)`);
  content = content.replace(rentalsRegex, `$1, ${data.rentalsAdditions}$2`);
  
  const authRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n)(\\s*auth: \\{)`);
  const replacement = `$1    ai: { ${data.ai} },\n    discovery: { ${data.discovery} },\n    constellations: { ${data.constellations} },\n    footer: { ${data.footer} },\n$2`;
  content = content.replace(authRegex, replacement);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Batch 2 injected successfully.');
