import fs from 'fs';

const path = 'C:\\Users\\alexa\\.gemini\\antigravity-ide\\scratch\\Gorgona-one-claude\\lib\\i18n.js';
let content = fs.readFileSync(path, 'utf8');

const translations = {
  fa: {
    navAdditions: "travel: 'سفر', villas: 'ویلاها', yachts: 'قایق‌های تفریحی', cars: 'ماشین‌ها', discovery: 'اتاق کشف'",
    homeAdditions: "heroEyebrow: 'پیشنهادات جهانی · کدهای تخفیف · مزایای سبک زندگی', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'کاوش در بازار', browseDeals: 'مرور پیشنهادات', askConcierge: 'از کانسیرج بپرسید', scrollExplore: 'برای کاوش به پایین بکشید', aiEyebrow: 'Gorgona One AI', aiTitle: 'به هوش مصنوعی بگویید چه می‌خواهید. اکوسیستم را پیدا می‌کند.', aiLede: 'یک کادر جستجو نیست — لایه هوشمند GORGONA ONE است. با نیت، به زبان خود، با صدا یا متن بپرسید.', ecosystemEyebrow: 'اکوسیستم', ecosystemTitle: 'هشت دنیا. یک عضویت.', ecosystemLede: 'سفر، خرید، اقامت، قایق‌های تفریحی، ماشین‌ها، شرط‌بندی ورزشی، رویدادها و یک کانسیرج هوش مصنوعی — هر تجربه در یک زبان طراحی لوکس واحد پیچیده شده است.', partnerEyebrow: 'شریک شدن با GORGONA ONE', partnerTitle: 'برند خود را درون یک اکوسیستم لوکس قرار دهید.', partnerLede: 'پیشنهادات تایید شده را منتشر کنید، مکان‌های متعدد را مدیریت کنید و در تمام بخش‌ها به مخاطبان جهانی پریمیوم برسید.', joinPartner: 'پیوستن به عنوان شریک', signIn: 'ورود'",
    rentalsAdditions: "fleet: 'ناوگان', collections: 'مجموعه‌ها', conciergeDelivery: 'تحویل کانسیرج', beyond: 'و فراتر از آن', conciergeEyebrow: 'کانسیرج', unforgettable: 'با یک چیز فراموش‌نشدنی برسید', whiteGlove: 'تحویل با دستکش سفید، ارسال به ویلا یا مارینای شما، و کانسیرج در هر مایل آماده به کار.', askConcierge: 'از کانسیرج بپرسید'",
    ai: "listening: 'در حال گوش دادن', surfacing: 'در حال جستجو', light: 'روشن', dark: 'تاریک', switchToLight: 'تغییر به فضای روشن', switchToDark: 'تغییر به فضای تاریک', askPlaceholder: 'از Gorgona One AI بپرسید', stopListening: 'توقف گوش دادن', speakRequest: 'درخواست خود را بگویید', discoveryRoom: 'اتاق کشف', askAnywhere: 'از هر جایی بپرسید...', ask: 'پرسش', results: 'نتایج', saved: 'ذخیره شده', pinResults: 'نتایج را پین کنید تا اینجا بمانند — هنگام مرور سر جای خود می‌مانند.', recentSearches: 'جستجوهای اخیر', clear: 'پاک کردن', searchesKept: 'جستجوهای شما اینجا ظاهر می‌شوند و در سراسر سایت حفظ می‌شوند.', reuseSearch: 'استفاده مجدد از این جستجو', returnToAI: 'بازگشت به Gorgona One AI', removeFromSaved: 'حذف از ذخیره شده‌ها', save: 'ذخیره', closeAI: 'بستن Gorgona One AI', openAI: 'باز کردن Gorgona One AI'",
    discovery: "travel: 'سفر', flights: 'پروازها', hotels: 'هتل‌ها', carRentals: 'اجاره ماشین', cars: 'ماشین‌ها', yachts: 'قایق‌های تفریحی', shopping: 'خرید', fashion: 'مد', beauty: 'زیبایی', electronics: 'الکترونیک', entertainment: 'سرگرمی', events: 'رویدادها', sports: 'ورزش', sportsbooks: 'شرط‌بندی ورزشی', food: 'غذا', restaurants: 'رستوران‌ها', concierge: 'کانسیرج', promoCodes: 'کدهای تخفیف', deals: 'پیشنهادات'",
    constellations: "travel: 'دنیای سفر', drive: 'رانندگی و دریانوردی', style: 'استایل و خرید', play: 'بازی و برنده شدن', taste: 'میز و طعم', concierge: 'کانسیرج'",
    footer: "ecosystemTitle: 'اکوسیستم', companyTitle: 'شرکت', legalTitle: 'حقوقی', desc: 'یک اکوسیستم لوکس برای سفر، خرید، اقامت، قایق‌های تفریحی، ماشین‌ها، شرط‌بندی ورزشی، رویدادها و کانسیرج هوش مصنوعی — پیشنهادات تایید شده و تجربیات پریمیوم در یک مقصد.', copyright: '© 2026 GORGONA ONE. معاملات پریمیوم، تخفیف‌های تایید شده و درآمدزایی وابسته آماده.', tagline: 'یک اکوسیستم لوکس متحد', partnerPortal: 'پورتال شرکا', becomePartner: 'تبدیل شدن به شریک', admin: 'مدیریت', privacy: 'حریم خصوصی', terms: 'شرایط', affiliateDisclosure: 'افشای همکاری', cookiePolicy: 'خط‌مشی کوکی'"
  },
  it: {
    navAdditions: "travel: 'Viaggi', villas: 'Ville', yachts: 'Yacht', cars: 'Auto', discovery: 'Stanza della Scoperta'",
    homeAdditions: "heroEyebrow: 'Offerte globali · Codici promozionali · Vantaggi lifestyle', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'Esplora il Marketplace', browseDeals: 'Sfoglia le offerte', askConcierge: 'Chiedi al Concierge', scrollExplore: 'Scorri per esplorare', aiEyebrow: 'Gorgona One AI', aiTitle: 'Dì all\\'IA cosa desideri. Lei trova l\\'ecosistema.', aiLede: 'Non è una casella di ricerca — è il livello di intelligenza di GORGONA ONE. Chiedi per intenzione, nella tua lingua, a voce o testualmente.', ecosystemEyebrow: 'L\\'Ecosistema', ecosystemTitle: 'Otto mondi. Un solo abbonamento.', ecosystemLede: 'Viaggi, shopping, soggiorni, yacht, auto, scommesse sportive, eventi e un concierge IA — ogni esperienza avvolta in un unico linguaggio di design di lusso.', partnerEyebrow: 'Diventa partner di GORGONA ONE', partnerTitle: 'Inserisci il tuo brand in un ecosistema di lusso.', partnerLede: 'Pubblica offerte verificate, gestisci più sedi e raggiungi un pubblico globale premium in tutte le sezioni.', joinPartner: 'Unisciti come Partner', signIn: 'Accedi'",
    rentalsAdditions: "fleet: 'La Flotta', collections: 'Collezioni', conciergeDelivery: 'Consegna dal concierge', beyond: 'e oltre', conciergeEyebrow: 'Concierge', unforgettable: 'Arriva con qualcosa di indimenticabile', whiteGlove: 'Ritiro in guanti bianchi, consegna alla tua villa o al porto, e un concierge a disposizione per ogni chilometro.', askConcierge: 'Chiedi al Concierge'",
    ai: "listening: 'In ascolto', surfacing: 'Ricerca in corso', light: 'Chiaro', dark: 'Scuro', switchToLight: 'Passa ad un\\'atmosfera chiara', switchToDark: 'Passa ad un\\'atmosfera scura', askPlaceholder: 'Chiedi a Gorgona One AI', stopListening: 'Interrompi ascolto', speakRequest: 'Esprimi la tua richiesta', discoveryRoom: 'Stanza della Scoperta', askAnywhere: 'Chiedi da qualsiasi luogo…', ask: 'Chiedi', results: 'Risultati', saved: 'Salvati', pinResults: 'Appunta i risultati per mantenerli qui — restano mentre navighi.', recentSearches: 'Ricerche recenti', clear: 'Cancella', searchesKept: 'Le tue ricerche appaiono qui e vengono mantenute in tutto il sito.', reuseSearch: 'Riusa questa ricerca', returnToAI: 'Torna a Gorgona One AI', removeFromSaved: 'Rimuovi dai salvati', save: 'Salva', closeAI: 'Chiudi Gorgona One AI', openAI: 'Apri Gorgona One AI'",
    discovery: "travel: 'Viaggi', flights: 'Voli', hotels: 'Hotel', carRentals: 'Noleggio Auto', cars: 'Auto', yachts: 'Yacht', shopping: 'Shopping', fashion: 'Moda', beauty: 'Bellezza', electronics: 'Elettronica', entertainment: 'Intrattenimento', events: 'Eventi', sports: 'Sport', sportsbooks: 'Scommesse', food: 'Cibo', restaurants: 'Ristoranti', concierge: 'Concierge', promoCodes: 'Codici Promo', deals: 'Offerte'",
    constellations: "travel: 'Mondo dei Viaggi', drive: 'Guida e Navigazione', style: 'Stile e Shopping', play: 'Gioca e Vinci', taste: 'Tavola e Gusto', concierge: 'Concierge'",
    footer: "ecosystemTitle: 'Ecosistema', companyTitle: 'Azienda', legalTitle: 'Legale', desc: 'Un ecosistema di lusso per viaggi, shopping, soggiorni, yacht, auto, scommesse sportive, eventi e un concierge IA — offerte verificate ed esperienze premium in un\\'unica destinazione.', copyright: '© 2026 GORGONA ONE. Offerte premium, sconti verificati e monetizzazione affiliati pronta.', tagline: 'Un ecosistema di lusso unificato', partnerPortal: 'Portale Partner', becomePartner: 'Diventa un Partner', admin: 'Amministrazione', privacy: 'Privacy', terms: 'Termini', affiliateDisclosure: 'Informativa Affiliati', cookiePolicy: 'Informativa sui Cookie'"
  },
  fr: {
    navAdditions: "travel: 'Voyage', villas: 'Villas', yachts: 'Yachts', cars: 'Voitures', discovery: 'Salle de Découverte'",
    homeAdditions: "heroEyebrow: 'Offres mondiales · Codes promo · Avantages lifestyle', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'Explorer le marché', browseDeals: 'Parcourir les offres', askConcierge: 'Demander au concierge', scrollExplore: 'Faites défiler pour explorer', aiEyebrow: 'Gorgona One AI', aiTitle: 'Dites à l\\'IA ce que vous voulez. Elle trouve l\\'écosystème.', aiLede: 'Ce n\\'est pas une barre de recherche — c\\'est la couche d\\'intelligence de GORGONA ONE. Demandez par intention, dans votre langue, à la voix ou par texte.', ecosystemEyebrow: 'L\\'Écosystème', ecosystemTitle: 'Huit mondes. Un seul abonnement.', ecosystemLede: 'Voyages, shopping, séjours, yachts, voitures, paris sportifs, événements et un concierge IA — chaque expérience enveloppée dans un langage de design de luxe unique.', partnerEyebrow: 'Devenez partenaire de GORGONA ONE', partnerTitle: 'Placez votre marque au sein d\\'un écosystème de luxe.', partnerLede: 'Publiez des offres vérifiées, gérez plusieurs emplacements et touchez un public mondial premium dans toutes les sections.', joinPartner: 'Rejoindre en tant que partenaire', signIn: 'Se connecter'",
    rentalsAdditions: "fleet: 'La Flotte', collections: 'Collections', conciergeDelivery: 'Livraison par le concierge', beyond: 'et au-delà', conciergeEyebrow: 'Concierge', unforgettable: 'Arrivez avec quelque chose d\\'inoubliable', whiteGlove: 'Prise en charge avec des gants blancs, livraison à votre villa ou marina, et un concierge à votre disposition à chaque kilomètre.', askConcierge: 'Demander au concierge'",
    ai: "listening: 'En écoute', surfacing: 'Recherche en cours', light: 'Clair', dark: 'Sombre', switchToLight: 'Passer à l\\'atmosphère claire', switchToDark: 'Passer à l\\'atmosphère sombre', askPlaceholder: 'Demandez à Gorgona One AI', stopListening: 'Arrêter l\\'écoute', speakRequest: 'Exprimez votre demande', discoveryRoom: 'Salle de Découverte', askAnywhere: 'Demandez de n\\'importe où…', ask: 'Demander', results: 'Résultats', saved: 'Sauvegardé', pinResults: 'Épinglez les résultats pour les garder ici — ils restent pendant que vous naviguez.', recentSearches: 'Recherches récentes', clear: 'Effacer', searchesKept: 'Vos recherches apparaissent ici et sont conservées sur tout le site.', reuseSearch: 'Réutiliser cette recherche', returnToAI: 'Retour à Gorgona One AI', removeFromSaved: 'Retirer des éléments sauvegardés', save: 'Sauvegarder', closeAI: 'Fermer Gorgona One AI', openAI: 'Ouvrir Gorgona One AI'",
    discovery: "travel: 'Voyage', flights: 'Vols', hôtels: 'Hôtels', carRentals: 'Location de voitures', cars: 'Voitures', yachts: 'Yachts', shopping: 'Shopping', fashion: 'Mode', beauty: 'Beauté', electronics: 'Électronique', entertainment: 'Divertissement', events: 'Événements', sports: 'Sports', sportsbooks: 'Paris sportifs', food: 'Nourriture', restaurants: 'Restaurants', concierge: 'Concierge', promoCodes: 'Codes Promo', deals: 'Offres'",
    constellations: "travel: 'Monde du Voyage', drive: 'Conduite et Voile', style: 'Style et Shopping', play: 'Jouer et Gagner', taste: 'Table et Goût', concierge: 'Concierge'",
    footer: "ecosystemTitle: 'Écosystème', companyTitle: 'Entreprise', legalTitle: 'Légal', desc: 'Un écosystème de luxe pour les voyages, le shopping, les séjours, les yachts, les voitures, les paris sportifs, les événements et un concierge IA — des offres vérifiées et des expériences premium en une seule destination.', copyright: '© 2026 GORGONA ONE. Offres premium, remises vérifiées et monétisation par affiliation prête.', tagline: 'Un écosystème de luxe unifié', partnerPortal: 'Portail Partenaires', becomePartner: 'Devenir Partenaire', admin: 'Administration', privacy: 'Confidentialité', terms: 'Conditions', affiliateDisclosure: 'Divulgation d\\'affiliation', cookiePolicy: 'Politique des Cookies'"
  },
  pl: {
    navAdditions: "travel: 'Podróże', villas: 'Wille', yachts: 'Jachty', cars: 'Samochody', discovery: 'Pokój Odkryć'",
    homeAdditions: "heroEyebrow: 'Globalne okazje · Kody promocyjne · Korzyści lifestyle', titleGorgona: 'GORGONA', titleOne: 'ONE', exploreMarketplace: 'Odkryj Marketplace', browseDeals: 'Przeglądaj oferty', askConcierge: 'Zapytaj Konsjerża', scrollExplore: 'Przewiń, aby odkryć', aiEyebrow: 'Gorgona One AI', aiTitle: 'Powiedz sztucznej inteligencji, czego chcesz. Ona znajdzie ekosystem.', aiLede: 'To nie jest pole wyszukiwania — to warstwa inteligencji GORGONA ONE. Pytaj z intencją, w swoim języku, głosem lub tekstem.', ecosystemEyebrow: 'Ekosystem', ecosystemTitle: 'Osiem światów. Jedno członkostwo.', ecosystemLede: 'Podróże, zakupy, pobyty, jachty, samochody, zakłady sportowe, wydarzenia i konsjerż AI — każde doświadczenie ubrane w jeden luksusowy język designu.', partnerEyebrow: 'Zostań partnerem GORGONA ONE', partnerTitle: 'Umieść swoją markę w luksusowym ekosystemie.', partnerLede: 'Publikuj zweryfikowane oferty, zarządzaj wieloma lokalizacjami i docieraj do globalnej, zamożnej publiczności we wszystkich sekcjach.', joinPartner: 'Dołącz jako Partner', signIn: 'Zaloguj się'",
    rentalsAdditions: "fleet: 'Flota', collections: 'Kolekcje', conciergeDelivery: 'Dostawa przez konsjerża', beyond: 'i dalej', conciergeEyebrow: 'Konsjerż', unforgettable: 'Przyjedź w czymś niezapomnianym', whiteGlove: 'Odbiór w białych rękawiczkach, dostawa do Twojej willi lub przystani i konsjerż na wezwanie z każdym kilometrem.', askConcierge: 'Zapytaj Konsjerża'",
    ai: "listening: 'Nasłuchiwanie', surfacing: 'Wyszukiwanie', light: 'Jasny', dark: 'Ciemny', switchToLight: 'Przełącz na jasną atmosferę', switchToDark: 'Przełącz na ciemną atmosferę', askPlaceholder: 'Zapytaj Gorgona One AI', stopListening: 'Zatrzymaj nasłuchiwanie', speakRequest: 'Wypowiedz swoje żądanie', discoveryRoom: 'Pokój Odkryć', askAnywhere: 'Pytaj z dowolnego miejsca…', ask: 'Zapytaj', results: 'Wyniki', saved: 'Zapisane', pinResults: 'Przypnij wyniki, aby zatrzymać je tutaj — pozostają na miejscu podczas przeglądania.', recentSearches: 'Ostatnie wyszukiwania', clear: 'Wyczyść', searchesKept: 'Twoje wyszukiwania pojawiają się tutaj i są zachowywane w całej witrynie.', reuseSearch: 'Użyj ponownie tego wyszukiwania', returnToAI: 'Wróć do Gorgona One AI', removeFromSaved: 'Usuń z zapisanych', save: 'Zapisz', closeAI: 'Zamknij Gorgona One AI', openAI: 'Otwórz Gorgona One AI'",
    discovery: "travel: 'Podróże', flights: 'Loty', hotels: 'Hotele', carRentals: 'Wynajem aut', cars: 'Samochody', yachts: 'Jachty', shopping: 'Zakupy', fashion: 'Moda', beauty: 'Uroda', electronics: 'Elektronika', entertainment: 'Rozrywka', events: 'Wydarzenia', sports: 'Sport', sportsbooks: 'Zakłady sportowe', food: 'Jedzenie', restaurants: 'Restauracje', concierge: 'Konsjerż', promoCodes: 'Kody Promocyjne', deals: 'Oferty'",
    constellations: "travel: 'Świat Podróży', drive: 'Jazda i Żeglarstwo', style: 'Styl i Zakupy', play: 'Graj i Wygrywaj', taste: 'Stół i Smak', concierge: 'Konsjerż'",
    footer: "ecosystemTitle: 'Ekosystem', companyTitle: 'Firma', legalTitle: 'Prawne', desc: 'Luksusowy ekosystem dla podróży, zakupów, pobytów, jachtów, samochodów, zakładów sportowych, wydarzeń i konsjerża AI — zweryfikowane oferty i doświadczenia premium w jednym miejscu.', copyright: '© 2026 GORGONA ONE. Oferty premium, zweryfikowane zniżki i gotowa monetyzacja partnerska.', tagline: 'Zunifikowany luksusowy ekosystem', partnerPortal: 'Portal Partnerski', becomePartner: 'Zostań Partnerem', admin: 'Administracja', privacy: 'Prywatność', terms: 'Warunki', affiliateDisclosure: 'Ujawnienie partnerskie', cookiePolicy: 'Polityka plików cookie'"
  }
};

for (const [lang, data] of Object.entries(translations)) {
  const navRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*nav: \\{.*?)( \\},?\\n)`);
  content = content.replace(navRegex, `$1, ${data.navAdditions}$2`);
  
  const homeRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*home: \\{.*?)( \\},?\\n)`);
  content = content.replace(homeRegex, `$1, ${data.homeAdditions}$2`);
  
  const rentalsRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n\\s*rentals: \\{.*?)( \\},?\\n)`);
  content = content.replace(rentalsRegex, `$1, ${data.rentalsAdditions}$2`);
  
  const authRegex = new RegExp(`(\\n\\s*\\b${lang}\\b: \\{[\\s\\S]*?\\n)(\\s*auth: \\{)`);
  const replacement = `$1    ai: { ${data.ai} },\n    discovery: { ${data.discovery} },\n    constellations: { ${data.constellations} },\n    footer: { ${data.footer} },\n$2`;
  content = content.replace(authRegex, replacement);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Batch 3 injected successfully.');
